use valence::item::ItemKind;

pub fn is_spawn_egg(item: &ItemKind) -> bool {
    matches!(
        item,
        ItemKind::AllaySpawnEgg
            | ItemKind::AxolotlSpawnEgg
            | ItemKind::BatSpawnEgg
            | ItemKind::BeeSpawnEgg
            | ItemKind::BlazeSpawnEgg
            | ItemKind::CatSpawnEgg
            | ItemKind::CamelSpawnEgg
            | ItemKind::CaveSpiderSpawnEgg
            | ItemKind::ChickenSpawnEgg
            | ItemKind::CodSpawnEgg
            | ItemKind::CowSpawnEgg
            | ItemKind::CreeperSpawnEgg
            | ItemKind::DolphinSpawnEgg
            | ItemKind::DonkeySpawnEgg
            | ItemKind::DrownedSpawnEgg
            | ItemKind::ElderGuardianSpawnEgg
            | ItemKind::EnderDragonSpawnEgg
            | ItemKind::EndermanSpawnEgg
            | ItemKind::EndermiteSpawnEgg
            | ItemKind::EvokerSpawnEgg
            | ItemKind::FoxSpawnEgg
            | ItemKind::FrogSpawnEgg
            | ItemKind::GhastSpawnEgg
            | ItemKind::GlowSquidSpawnEgg
            | ItemKind::GoatSpawnEgg
            | ItemKind::GuardianSpawnEgg
            | ItemKind::HoglinSpawnEgg
            | ItemKind::HorseSpawnEgg
            | ItemKind::HuskSpawnEgg
            | ItemKind::IronGolemSpawnEgg
            | ItemKind::LlamaSpawnEgg
            | ItemKind::MagmaCubeSpawnEgg
            | ItemKind::MooshroomSpawnEgg
            | ItemKind::MuleSpawnEgg
            | ItemKind::OcelotSpawnEgg
            | ItemKind::PandaSpawnEgg
            | ItemKind::ParrotSpawnEgg
            | ItemKind::PhantomSpawnEgg
            | ItemKind::PigSpawnEgg
            | ItemKind::PiglinSpawnEgg
            | ItemKind::PiglinBruteSpawnEgg
            | ItemKind::PillagerSpawnEgg
            | ItemKind::PolarBearSpawnEgg
            | ItemKind::PufferfishSpawnEgg
            | ItemKind::RabbitSpawnEgg
            | ItemKind::RavagerSpawnEgg
            | ItemKind::SalmonSpawnEgg
            | ItemKind::SheepSpawnEgg
            | ItemKind::ShulkerSpawnEgg
            | ItemKind::SilverfishSpawnEgg
            | ItemKind::SkeletonSpawnEgg
            | ItemKind::SkeletonHorseSpawnEgg
            | ItemKind::SlimeSpawnEgg
            | ItemKind::SnifferSpawnEgg
            | ItemKind::SnowGolemSpawnEgg
            | ItemKind::SpiderSpawnEgg
            | ItemKind::SquidSpawnEgg
            | ItemKind::StraySpawnEgg
            | ItemKind::StriderSpawnEgg
            | ItemKind::TadpoleSpawnEgg
            | ItemKind::TraderLlamaSpawnEgg
            | ItemKind::TropicalFishSpawnEgg
            | ItemKind::TurtleSpawnEgg
            | ItemKind::VexSpawnEgg
            | ItemKind::VillagerSpawnEgg
            | ItemKind::VindicatorSpawnEgg
            | ItemKind::WanderingTraderSpawnEgg
            | ItemKind::WardenSpawnEgg
            | ItemKind::WitchSpawnEgg
            | ItemKind::WitherSpawnEgg
            | ItemKind::WitherSkeletonSpawnEgg
            | ItemKind::WolfSpawnEgg
            | ItemKind::ZoglinSpawnEgg
            | ItemKind::ZombieSpawnEgg
            | ItemKind::ZombieHorseSpawnEgg
            | ItemKind::ZombieVillagerSpawnEgg
            | ItemKind::ZombifiedPiglinSpawnEgg
    )
}
